cluster.routing.allocation.disk.watermark.low: {{watermark_low}}
cluster.routing.allocation.disk.watermark.high: {{watermark_high}}
cluster.routing.allocation.disk.watermark.flood_stage: {{watermark_flood_stage}}
